name = "bomrecheio-salgaderia"
compatibility_date = "2026-08-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "bom-recheio-db"
database_id = "0bda5c22-a337-44e9-bf98-82107c3eff69"
migrations_dir = "migrations"